### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by macMikey** [miyako/language-4dpreferences#1]
Installing “language-4dpreferences@0.15.1” failed.Hide output…
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/me/.atom/packages/language-4dpreferences/node_modules/npm/node_modules/split-on-first/index.d.ts'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:696:12)
    at WriteStream.emit (events.js:182:13)
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:211:14
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:169:20)

**Comment by miyako** [comment]
what atom version?
